<?php 

$labels = array(
		'name'                  => _x( 'Clients', 'Post Type General Name', 'fyc' ),
		'singular_name'         => _x( 'Client', 'Post Type Singular Name', 'fyc' ),
		'menu_name'             => __( 'Clients', 'fyc' ),
		'name_admin_bar'        => __( 'Client', 'fyc' ),
		'archives'              => __( 'Client Archives', 'fyc' ),
		'attributes'            => __( 'Client Attributes', 'fyc' ),
		'parent_item_colon'     => __( 'Parent Item:', 'fyc' ),
		'all_items'             => __( 'All Clients', 'fyc' ),
		'add_new_item'          => __( 'Add New Client', 'fyc' ),
		'add_new'               => __( 'Add New', 'fyc' ),
		'new_item'              => __( 'New Client', 'fyc' ),
		'edit_item'             => __( 'Edit Client', 'fyc' ),
		'update_item'           => __( 'Update Client', 'fyc' ),
		'view_item'             => __( 'View Client', 'fyc' ),
		'view_items'            => __( 'View IClient', 'fyc' ),
		'search_items'          => __( 'Search Client', 'fyc' ),
		'not_found'             => __( 'Not found', 'fyc' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'fyc' ),
		'featured_image'        => __( 'Featured Image', 'fyc' ),
		'set_featured_image'    => __( 'Set featured image', 'fyc' ),
		'remove_featured_image' => __( 'Remove featured image', 'fyc' ),
		'use_featured_image'    => __( 'Use as featured image', 'fyc' ),
		'insert_into_item'      => __( 'Insert into Client', 'fyc' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Client', 'fyc' ),
		'items_list'            => __( 'Clients list', 'fyc' ),
		'items_list_navigation' => __( 'Clients list navigation', 'fyc' ),
		'filter_items_list'     => __( 'Filter Clients list', 'fyc' ),
	);
	$args = array(
		'label'                 => __( 'Client', 'fyc' ),
		'description'           => __( 'Your clients. Duh!', 'fyc' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'revisions' ),
		'taxonomies'            => array( 'category' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => $show_in_menu,
		'menu_position'         => 12,
		'menu_icon'             => 'dashicons-groups',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'rewrite'               => false,
		'capability_type'       => 'post',
		'show_in_rest'          => true,
		'rest_base'             => 'client',
	);
	register_post_type( 'client', $args );
